version: '3'
services:
  es01:
    image: docker.elastic.co/elasticsearch/elasticsearch:7.15.1
    container_name: es01
    environment:
      - discovery.type=single-node
      - bootstrap.memory_lock=true
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
    ulimits:
      memlock:
        soft: -1
        hard: -1
    volumes:
      - data01:/usr/share/elasticsearch/data
    ports:
      - 9200:9200
    networks:
      - elastic

  lgst01:
    image: docker.elastic.co/logstash/logstash:7.15.1
    container_name: lgst01
    ports:
      - 9600:9600
#      - 8089:8089
    environment:
      - "ES_JAVA_OPTS=-Xms4g-Xmx4g"
    ulimits:
      memlock:
        soft: -1
        hard: -1
    volumes:
      - /home/elk/config/:/usr/share/logstash/pipeline/
      - /home/elk/load/:/usr/share/logstash/load/
    depends_on:
      - es01
    networks:
      - elastic

  kib01:
    image: docker.elastic.co/kibana/kibana:7.15.1
    container_name: kib01
    ports:
      - 5601:5601
    environment:
      ELASTICSEARCH_URL: http://es01:9200
      ELASTICSEARCH_HOSTS: '["http://es01:9200"]'
    depends_on:
      - es01
    networks:
      - elastic

volumes:
  data01:
    driver: local

networks:
  elastic:
    driver: bridge
